alter table ASSETMANAGEMENT_ADD_ASSET add constraint FK_ASSETMANAGEMENT_ADD_ASSET_NAME foreign key (NAME_ID) references ASSETMANAGEMENT_ASSET(ID);
create index IDX_ASSETMANAGEMENT_ADD_ASSET_NAME on ASSETMANAGEMENT_ADD_ASSET (NAME_ID);
