alter table ASSETMANAGEMENT_ADD_ASSET_ASSET_LINK add constraint FK_AAAAL_ADD_ASSET foreign key (ADD_ASSET_ID) references ASSETMANAGEMENT_ADD_ASSET(ID);
alter table ASSETMANAGEMENT_ADD_ASSET_ASSET_LINK add constraint FK_AAAAL_ASSET foreign key (ASSET_ID) references ASSETMANAGEMENT_ASSET(ID);
