alter table ASSETMANAGEMENT_SELECTASSET add constraint FK_ASSETMANAGEMENT_SELECTASSET_NAME foreign key (NAME_ID) references ASSETMANAGEMENT_ADD_ASSET(ID);
create index IDX_ASSETMANAGEMENT_SELECTASSET_NAME on ASSETMANAGEMENT_SELECTASSET (NAME_ID);
